### ISSUE TITLE
Modified attribute is duplicated in output

### ISSUE THREAD

**Issue by fyodorovich** [rpeyron/libxmldiff#1] opened 2018-06-11 01:09 UTC
When running xmldiff, sometimes the modified attribute value is duplicated, as shown below.

creationDate="19/03/2018|20/03/2018|20/03/2018"

I've attached the xml inputs and the output from xmldiff.

[Archive.zip](https://github.com/rpeyron/libxmldiff/files/2088423/Archive.zip)

**Comment by rpeyron** [comment] 2018-06-12 21:06
I was not able to reproduce with the files you provided:
-  Do you always observe the bug or does it occur randomly ?  
- Could you add the command line you used and your configuration/environment (OS, xmldiff version,...) ? 

Thanks

**Comment by fyodorovich** [comment] 2018-06-12 22:04
Hi Remi,

I will look more closely.  I am not seeing the bug now.  The problem occurred reliably with the files that I provided throughout two days of testing. I had been messing around with the environment, trying to build xmlnavtree on my MacBook. That may have caused problems. 

thanks,

Malcolm

**Comment by rpeyron** [comment] 2018-06-13 22:45
Ok. I close this issue for now and will reopen it if you observe this again.

**Closed as completed by rpeyron** 2018-06-13 22:45 UTC
