### ISSUE TITLE
False Positives found in CDATA

### ISSUE THREAD

**Issue by fyodorovich** [rpeyron/libxmldiff#2] opened 2018-06-11 01:17 UTC
Using xmldiff I have found false positives in the output when calling it like this:

xmldiff diff --keep-diff-only yes $old $new

The attached files show the problem. A simple diff reveals that there is change to CDATA and children in one node. The output from xmldiff shows modifications in two other CDATA sections.

[Archive.zip](https://github.com/rpeyron/libxmldiff/files/2088434/Archive.zip)

**Comment by rpeyron** [comment] 2018-06-12 22:03
Thanks for reporting.

Just to be sure, is the problem in the output of 
```
<Calculation table="CTT Address" diff:status="below"><![CDATA[rec_pid]]><![CDATA[Case ( 
status_deleted ; "DEL";
status_archived; "ARK";
"")
& rec_pid]]></Calculation>
```
?

It seems that the behaviour of xmldiff with CDATA sections is not correct:  CDATA sections are currently treated as separate nodes. In this case, the algorithm sees one node CDATA with a text A in the old file and one node CDATA with a text B in the new file. It considers that the first CDATA "A" has been removed, and the second "B" has been added. That why you see both CDATA sections in the output. It tries to add diff:status attribute to the node, but as attributes are not written on CDATA nodes, that's why you won't see it. You may have a vizualisation of what I am saying with diffing the two files in xmlTreeNav.

That said, this is obviously not a good behaviour. I am not sure what should be the good one: treat CDATA like text, with an output like:
```
              <Calculation table="CTT Address" diff:status="**modified**"><![CDATA[rec_pid**|**Case ( 
status_deleted ; "DEL";
status_archived; "ARK";
"")
& rec_pid]]></Calculation>
```
But it has also many drawbacks: the separator with large/multiline CDATA would be hard to find, that will be complicated with mixed/multiples text/cdata sections (for multiple text nodes, all nodes are merged),...

-> What should be the result you would expect in your case ?

(Note that the same question applies to comments and PI nodes)

Btw found a bug in xmlTreeNav with displaying CDATA nodes while working on this bug ; will investigate that too :)

**Comment by fyodorovich** [comment] 2018-06-12 23:16
Hi Remi,

The issue of false positives being reported in CDATA has also disappeared, so I think that I may have messed up my environment for a while. ( Fortunately, macPorts has put things right ).

The explanation makes sense.  It allows me to understand the problem. 

Looking at the output I can see one thing which is curious. In all other cases where there is a difference the output returns "old value separator new value". For CDATA the output returns "new value separator old value". 

A second thing. This is unrelated to CDATA but the issue arises near CDATA in my code. The XML I work with contains the text entered by the user as CDATA in the Calculation element. It also contains the tokenised representation of the text as Chunks in the DisplayCalculation element. In this text below, the original DisplayCalculation element has seven Chunks. Chunks one to six were removed. Chunk seven was not modified. The new DisplayCalculation element has one chunk. The output does not recognise this. It behaves as if chunk one was modified and has to describe the modifications.  In addition, the order of the chunk elements is  changed. While the output is correct, it is very hard to work with, especially as the sequence of the Chunks in the output seems random. 

thanks for producing such a useful tool, I am very glad to be able to use it,



Malcolm Fitzgerald
Business Data Systems
Providing Web services, iOS Apps and Business Systems
ph: +64 221 6949 14
www.businessdatasystems.co.nz

**Comment by fyodorovich** [comment] 2018-06-12 23:22
hi Remi,

I forgot to include the inputs and the ouput for my email. Here it is.


********** old xml snippet ******************
            <Field id="1" dataType="Text" fieldType="Normal" name="id">
                <Comment/>
                <AutoEnter allowEditing="True" overwriteExistingValue="True" alwaysEvaluate="False" constant="False" furigana="False" lookup="False" calculation="True">
                    <ConstantData/>
                    <Calculation table="CTT Address"><![CDATA[Case ( 
status_deleted ; "DEL";
status_archived; "ARK";
"")
& rec_pid]]></Calculation>
                    <DisplayCalculation>
                        <Chunk type="FunctionRef">Case</Chunk>
                        <Chunk type="NoRef"> ( 
</Chunk>
                        <Chunk type="FieldRef">
                            <Field table="CTT Address" id="12" name="status_deleted"/>
                        </Chunk>
                        <Chunk type="NoRef"> ; &quot;DEL&quot;;
</Chunk>
                        <Chunk type="FieldRef">
                            <Field table="CTT Address" id="13" name="status_archived"/>
                        </Chunk>
                        <Chunk type="NoRef">; &quot;ARK&quot;;
&quot;&quot;)
&amp; </Chunk>
                        <Chunk type="FieldRef">
                            <Field table="CTT Address" id="10" name="rec_pid"/>
                        </Chunk>
                    </DisplayCalculation>
                </AutoEnter>
            </Field>



********** new xml snippet ******************
            <Field id="1" dataType="Text" fieldType="Normal" name="id">
                <Comment/>
                <AutoEnter allowEditing="True" overwriteExistingValue="True" alwaysEvaluate="False" constant="False" furigana="False" lookup="False" calculation="True">
                    <ConstantData/>
                    <Calculation table="CTT Address"><![CDATA[rec_pid]]></Calculation>
                    <DisplayCalculation>
                        <Chunk type="FieldRef">
                            <Field table="CTT Address" id="10" name="rec_pid"/>
                        </Chunk>
                    </DisplayCalculation>
                </AutoEnter>
            </Field>



************ output *******************
          <Field id="1" dataType="Text" fieldType="Normal" name="id" diff:status="below">
            <AutoEnter allowEditing="True" overwriteExistingValue="True" alwaysEvaluate="False" constant="False" furigana="False" lookup="False" calculation="True" diff:status="below">
              <Calculation table="CTT Address" diff:status="below"><![CDATA[rec_pid]]><![CDATA[Case ( 
status_deleted ; "DEL";
status_archived; "ARK";
"")
& rec_pid]]></Calculation>
              <DisplayCalculation diff:status="below">
                <Chunk type="FunctionRef|FieldRef" diff:status="modified">Case|<Field table="CTT Address" id="10" name="rec_pid" diff:status="added"/></Chunk>
                <Chunk type="FieldRef" diff:status="removed">
                  <Field table="CTT Address" id="10" name="rec_pid" diff:status="removed"/>
                </Chunk>
                <Chunk type="NoRef" diff:status="removed">; "ARK";
"")
&amp; </Chunk>
                <Chunk type="FieldRef" diff:status="removed">
                  <Field table="CTT Address" id="13" name="status_archived" diff:status="removed"/>
                </Chunk>
                <Chunk type="NoRef" diff:status="removed"> ; "DEL";
</Chunk>
                <Chunk type="FieldRef" diff:status="removed">
                  <Field table="CTT Address" id="12" name="status_deleted" diff:status="removed"/>
                </Chunk>
                <Chunk type="NoRef" diff:status="removed"> ( 
</Chunk>
              </DisplayCalculation>
            </AutoEnter>
          </Field>














> On 13/06/2018, at 10:03 AM, Remi Peyronnet <notifications@github.com> wrote:
> 
> Thanks for reporting.
> 
> Just to be sure, is the problem in the output of
> 
> <Calculation table="CTT Address" diff:status="below"><![CDATA[rec_pid]]><![CDATA[Case ( 
> status_deleted ; "DEL";
> status_archived; "ARK";
> "")
> & rec_pid]]></Calculation>
> 
> ?
> 
> It seems that the behaviour of xmldiff with CDATA sections is not correct: CDATA sections are currently treated as separate nodes. In this case, the algorithm sees one node CDATA with a text A in the old file and one node CDATA with a text B in the new file. It considers that the first CDATA "A" has been removed, and the second "B" has been added. That why you see both CDATA sections in the output. It tries to add diff:status attribute to the node, but as attributes are not written on CDATA nodes, that's why you won't see it. You may have a vizualisation of what I am saying with diffing the two files in xmlTreeNav.
> 
> That said, this is obviously not a good behaviour. I am not sure what should be the good one: treat CDATA like text, with an output like:
> 
>               <Calculation table="CTT Address" diff:status="**modified**"><![CDATA[rec_pid**|**Case ( 
> status_deleted ; "DEL";
> status_archived; "ARK";
> "")
> & rec_pid]]></Calculation>
> 
> But it has also many drawbacks: the separator with large/multiline CDATA would be hard to find, that will be complicated with mixed/multiples text/cdata sections (for multiple text nodes, all nodes are merged),...
> 
> -> What should be the result you would expect in your case ?
> 
> (Note that the same question applies to comments and PI nodes)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Malcolm Fitzgerald
Business Data Systems
Providing Web services, iOS Apps and Business Systems
ph: +64 221 6949 14
www.businessdatasystems.co.nz

**Comment by rpeyron** [comment] 2018-06-13 22:43
Hi Malcolm,

1/ About the false positives that disappeared, I noticed in your output.xml file that some differences were only a space, like in 
```
                <Chunk type="NoRef" diff:status="modified">
	; 	1 + | 
	; 	1 + </Chunk>
```
You will need to show spaces to see the difference. 

You may observe this with files treated with different CR/LF encoding, or that may probably be relative to your previous environment problems. Note that if you experience this again there is an option to force cleaning spaces before diffing (--force-clean yes)

2/ About the behavior you observed in Chunk nodes, with one marked as modified and the other as removed, this is how xmldiff works : for identifying matching items, it requires you provide an identifier field to help xmldiff  to find matching items, regardless of their position. By default, the attributes @id and @value are used (option --ids to change this). When no identifier is given, xmldiff just use the order of childs in the tree. In the chunk section you do not have @id attributes on the Chunk nodes, so xmldiff rely only on position : that is why you see the first as modified and the others as removed. In your case, you may want to use --ids @id,@type,Field . XPath expressions are currently not supported but you can use attributes or child elements text. If you need more complex id creation (by example if you need to use the id attribute of the Field node child to identify the Chunk node) I suggest to make a simple XSL pre-processing (that's why xmldiff supports XSL and scripts). It is a little complication to set it up the first time, but it will boost xmldiff power.

3/ About the order of Chunk nodes, I was not able to reproduce it. The output order should be as below:
- when there is identifier for the node, the output will be sorted by identifier
- when there is no identifier, the output should be based on the one of the new file

4/ About the "new value separator old value" I am note sure to have seen it. Could you point me out the example ?  if you refer to `<![CDATA[rec_pid]]><![CDATA[Case (` please note there is no separator. The order follow the rule described above with the first CDATA node of the output file (added), and then the one of the old file (removed). I agree this it not well handled. Should change that in the future.

I keep this issue open to solve the bad CDATA behaviour. About 1/,2/,3/, I hope my answer helps to understand how xmldiff. If one of these points do not fit your needs, please tell, and maybe open another issue to help to not forget one of the points.

**Comment by fyodorovich** [comment] 2018-06-14 00:07
Hi Remi,

thanks for looking so closely at these issues. 

1/ Sorry for wasting your time with that one. I had thought that the two files were both originals but it appears as though one of them has been touched by a different text editor.

2/ I'll follow your advice and explore XSL pre-processing.

3/ thanks for your explanation. The output describes all of the changes, so it is correct, and I'm happy to work with it as it is. 

4/ In a simple situation, say an attribute value is changed, the output is described like this: key="old|new". However, when CDATA is changed it appears in the opposite order <![CDATA[new]]><![CDATA[old]]>. 

The XML I'm processing includes a lot of CDATA. I'm using SimpleXML to parse the output and it returns both nodes as a single string. Having a separator would not really help as the CDATA I work with often includes pipes and other symbols. I would have no way to determine which was the real separator except in the simplest cases. To handle this, I obtain the id of the element that has been modified from the output then load both the old and new documents to access it's CDATA. The original files can be quite large, so I'd like to be able to use the CDATA from the output file for this but I haven't found a way to do that yet.

Malcolm

**Closed as completed** 2019-04-22 13:40 UTC

**Comment by rpeyron** [comment] 2019-04-22 15:00
Fixed CDATA wrong handling by adding two options "--special-nodes-ids no" that allow to specify not to use the content as ids for CData,PI, and comment, and "--special-nodes-before-value yes" to have before and after values.  Default settings are set in order not to modify the previous behaviour.
